permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

name: Eeshaan Jain
url: eeshaanjain.github.io
enforce_ssl: eeshaanjain.github.io
description: Eeshaan's personal website

exclude:
  - legacy
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: blog-post
