permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

name: Eeshaan Jain
url: eeshaanjain.github.io
enforce_ssl: eeshaanjain.github.io
description: Eeshaan's personal website

collections:
  ml:
    output: true
  math:
    output: true

defaults:
  - scope:
      path: ""
      type: ml
    values:
      layout: post
  - scope:
      path: ""
      type: math
    values:
      layout: post
